# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: event-schemas/competition.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC, 6, 31, 1, "", "event-schemas/competition.proto"
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import shared_pb2 as event__schemas_dot_shared__pb2
from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x1f\x65vent-schemas/competition.proto\x12\x0b\x63ompetition\x1a\x1a\x65vent-schemas/shared.proto\x1a\x1fgoogle/protobuf/timestamp.proto"\xa7\x01\n\x15UserCompetitionJoined\x12#\n\x06header\x18\x01 \x01(\x0b\x32\x13.shared.EventHeader\x12\x16\n\x0e\x63ompetition_id\x18\x02 \x01(\t\x12\x0f\n\x07user_id\x18\x03 \x01(\t\x12-\n\tjoined_at\x18\x04 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x11\n\twith_gift\x18\x05 \x01(\x08\x42*Z(internal/api/event_schemas;event_schemasb\x06proto3'
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(
    DESCRIPTOR, "event_schemas.competition_pb2", _globals
)
if not _descriptor._USE_C_DESCRIPTORS:
    _globals["DESCRIPTOR"]._loaded_options = None
    _globals["DESCRIPTOR"]._serialized_options = (
        b"Z(internal/api/event_schemas;event_schemas"
    )
    _globals["_USERCOMPETITIONJOINED"]._serialized_start = 110
    _globals["_USERCOMPETITIONJOINED"]._serialized_end = 277
# @@protoc_insertion_point(module_scope)
