# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import finance_pb2 as event__schemas_dot_finance__pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in event_schemas/finance_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class BalanceServiceStub(object):
    """gRPC API for applying rules to user events.
    service RuleService {
    Apply a rule for a single event item.
    rpc ApplyRule(ApplyRuleRequest) returns (ApplyRuleResponse);
    // Apply a rule for a batch of event items.
    rpc ApplyRuleBatch(BatchApplyRuleRequest) returns (BatchApplyRuleResponse);
    }

    service for Getting balance
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetBalance = channel.unary_unary(
                '/finance.BalanceService/GetBalance',
                request_serializer=event__schemas_dot_finance__pb2.GetBalanceRequest.SerializeToString,
                response_deserializer=event__schemas_dot_finance__pb2.GetBalanceResponse.FromString,
                _registered_method=True)


class BalanceServiceServicer(object):
    """gRPC API for applying rules to user events.
    service RuleService {
    Apply a rule for a single event item.
    rpc ApplyRule(ApplyRuleRequest) returns (ApplyRuleResponse);
    // Apply a rule for a batch of event items.
    rpc ApplyRuleBatch(BatchApplyRuleRequest) returns (BatchApplyRuleResponse);
    }

    service for Getting balance
    """

    def GetBalance(self, request, context):
        """for get balance by User_id
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_BalanceServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetBalance': grpc.unary_unary_rpc_method_handler(
                    servicer.GetBalance,
                    request_deserializer=event__schemas_dot_finance__pb2.GetBalanceRequest.FromString,
                    response_serializer=event__schemas_dot_finance__pb2.GetBalanceResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'finance.BalanceService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('finance.BalanceService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class BalanceService(object):
    """gRPC API for applying rules to user events.
    service RuleService {
    Apply a rule for a single event item.
    rpc ApplyRule(ApplyRuleRequest) returns (ApplyRuleResponse);
    // Apply a rule for a batch of event items.
    rpc ApplyRuleBatch(BatchApplyRuleRequest) returns (BatchApplyRuleResponse);
    }

    service for Getting balance
    """

    @staticmethod
    def GetBalance(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/finance.BalanceService/GetBalance',
            event__schemas_dot_finance__pb2.GetBalanceRequest.SerializeToString,
            event__schemas_dot_finance__pb2.GetBalanceResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
