deployments:
  enabled: true
  apps:
    finance-api:
      replicaCount: 1
      containers:
        - name: finance-api
          image: ${CI_REGISTRY}/applications/${CI_PROJECT_NAME}:${CI_COMMIT_SHORT_SHA}
          imagePullPolicy: IfNotPresent
          command:
            - gunicorn
            - -c
            - python:app.infrastructure.gunicorn.config
            - app.main:app
          envFrom:
            - secretRef:
                name: finance-api
          ports:
          - containerPort: 8000
    finance-inbox-worker:
      replicaCount: 1
      containers:
        - name: finance-inbox-worker
          image: ${CI_REGISTRY}/applications/${CI_PROJECT_NAME}:${CI_COMMIT_SHORT_SHA}
          imagePullPolicy: IfNotPresent
          command:
            - python
            - -m
            - app.infrastructure.rabbitmq.inbox_consumer
          envFrom:
            - secretRef:
                name: finance-inbox-worker
    finance-batch-worker:
      replicaCount: 1
      containers:
        - name: finance-batch-worker
          image: ${CI_REGISTRY}/applications/${CI_PROJECT_NAME}:${CI_COMMIT_SHORT_SHA}
          imagePullPolicy: IfNotPresent
          command:
            - python
            - -m
            - app.infrastructure.rabbitmq.batch_worker
            - --env-file
            - /dev/null
          envFrom:
            - secretRef:
                name: finance-batch-worker



services:
  enabled: true
  rules:
    finance-api:
      deployment: finance-api
      ports:
        - name: http
          protocol: TCP
          port: 8000
          targetPort: 8000



secrets:
  finance-api:
    annotations:
      vault.security.banzaicloud.io/vault-role: "finance-59-prod"
      vault.security.banzaicloud.io/vault-addr: "https://vault.tmbiz.info"
      vault.security.banzaicloud.io/vault-tls-secret: "vault.tmbiz.info-tls"
    data:
      APP_ENABLE_INBOX_CONSUMER: vault:production/data/tmbiz-info/finance/app#APP_ENABLE_INBOX_CONSUMER
      APP_ENABLE_METRICS: vault:production/data/tmbiz-info/finance/app#APP_ENABLE_METRICS
      APP_ENV: vault:production/data/tmbiz-info/finance/app#APP_ENV
      APP_HOST: vault:production/data/tmbiz-info/finance/app#APP_HOST
      APP_LOG_LEVEL: vault:production/data/tmbiz-info/finance/app#APP_LOG_LEVEL
      APP_NAME: vault:production/data/tmbiz-info/finance/app#APP_NAME
      APP_PORT: vault:production/data/tmbiz-info/finance/app#APP_PORT
      COMPETITION_FREEZE_DATETIME: vault:production/data/tmbiz-info/finance/app#COMPETITION_FREEZE_DATETIME
      GUNICORN_LOG_LEVEL: vault:production/data/tmbiz-info/finance/app#GUNICORN_LOG_LEVEL
      GUNICORN_TIMEOUT: vault:production/data/tmbiz-info/finance/app#GUNICORN_TIMEOUT
      GUNICORN_WORKERS: vault:production/data/tmbiz-info/finance/app#GUNICORN_WORKERS
      JWT_SECRET_KEY: vault:production/data/tmbiz-info/finance/app#JWT_SECRET_KEY
      JWT_SERVICE_API_KEY: vault:production/data/tmbiz-info/finance/app#JWT_SERVICE_API_KEY
      POSTGRES_DB: vault:production/data/tmbiz-info/finance/app#POSTGRES_DB
      POSTGRES_HOST: vault:production/data/tmbiz-info/finance/app#POSTGRES_HOST
      POSTGRES_PASSWORD: vault:production/data/tmbiz-info/finance/app#POSTGRES_PASSWORD
      POSTGRES_POOL_MAX: vault:production/data/tmbiz-info/finance/app#POSTGRES_POOL_MAX
      POSTGRES_POOL_MIN: vault:production/data/tmbiz-info/finance/app#POSTGRES_POOL_MIN
      POSTGRES_PORT: vault:production/data/tmbiz-info/finance/app#POSTGRES_PORT
      POSTGRES_USER: vault:production/data/tmbiz-info/finance/app#POSTGRES_USER
      RABBITMQ_HOST: vault:production/data/tmbiz-info/finance/app#RABBITMQ_HOST
      RABBITMQ_PASSWORD: vault:production/data/tmbiz-info/finance/app#RABBITMQ_PASSWORD
      RABBITMQ_PORT: vault:production/data/tmbiz-info/finance/app#RABBITMQ_PORT
      RABBITMQ_USER: vault:production/data/tmbiz-info/finance/app#RABBITMQ_USER
      REDIS_DB: vault:production/data/tmbiz-info/finance/app#REDIS_DB
      REDIS_HOST: vault:production/data/tmbiz-info/finance/app#REDIS_HOST
      REDIS_PASSWORD: vault:production/data/tmbiz-info/finance/app#REDIS_PASSWORD
      REDIS_PORT: vault:production/data/tmbiz-info/finance/app#REDIS_PORT
      USER_MANAGEMENT_API_KEY: vault:production/data/tmbiz-info/finance/app#USER_MANAGEMENT_API_KEY
  finance-inbox-worker:
    annotations:
      vault.security.banzaicloud.io/vault-role: "finance-59-prod"
      vault.security.banzaicloud.io/vault-addr: "https://vault.tmbiz.info"
      vault.security.banzaicloud.io/vault-tls-secret: "vault.tmbiz.info-tls"
    data:
      APP_ENABLE_METRICS: vault:production/data/tmbiz-info/finance/inbox-worker#APP_ENABLE_METRICS
      APP_ENV: vault:production/data/tmbiz-info/finance/inbox-worker#APP_ENV
      APP_LOG_LEVEL: vault:production/data/tmbiz-info/finance/inbox-worker#APP_LOG_LEVEL
      APP_NAME: vault:production/data/tmbiz-info/finance/inbox-worker#APP_NAME
      POSTGRES_DB: vault:production/data/tmbiz-info/finance/inbox-worker#POSTGRES_DB
      POSTGRES_HOST: vault:production/data/tmbiz-info/finance/inbox-worker#POSTGRES_HOST
      POSTGRES_PASSWORD: vault:production/data/tmbiz-info/finance/inbox-worker#POSTGRES_PASSWORD
      POSTGRES_POOL_MAX: vault:production/data/tmbiz-info/finance/inbox-worker#POSTGRES_POOL_MAX
      POSTGRES_POOL_MIN: vault:production/data/tmbiz-info/finance/inbox-worker#POSTGRES_POOL_MIN
      POSTGRES_PORT: vault:production/data/tmbiz-info/finance/inbox-worker#POSTGRES_PORT
      POSTGRES_USER: vault:production/data/tmbiz-info/finance/inbox-worker#POSTGRES_USER
      RABBITMQ_HOST: vault:production/data/tmbiz-info/finance/inbox-worker#RABBITMQ_HOST
      RABBITMQ_PASSWORD: vault:production/data/tmbiz-info/finance/inbox-worker#RABBITMQ_PASSWORD
      RABBITMQ_PORT: vault:production/data/tmbiz-info/finance/inbox-worker#RABBITMQ_PORT
      RABBITMQ_USER: vault:production/data/tmbiz-info/finance/inbox-worker#RABBITMQ_USER
  finance-batch-worker:
    annotations:
      vault.security.banzaicloud.io/vault-role: "finance-59-prod"
      vault.security.banzaicloud.io/vault-addr: "https://vault.tmbiz.info"
      vault.security.banzaicloud.io/vault-tls-secret: "vault.tmbiz.info-tls"
    data:
      APP_ENABLE_METRICS: vault:production/data/tmbiz-info/finance/batch-worker#APP_ENABLE_METRICS
      APP_ENV: vault:production/data/tmbiz-info/finance/batch-worker#APP_ENV
      APP_LOG_LEVEL: vault:production/data/tmbiz-info/finance/batch-worker#APP_LOG_LEVEL
      APP_NAME: vault:production/data/tmbiz-info/finance/batch-worker#APP_NAME
      BATCH_INTERVAL_SECONDS: vault:production/data/tmbiz-info/finance/batch-worker#BATCH_INTERVAL_SECONDS
      BATCH_SIZE: vault:production/data/tmbiz-info/finance/batch-worker#BATCH_SIZE
      INBOX_CLEANUP_DAYS: vault:production/data/tmbiz-info/finance/batch-worker#INBOX_CLEANUP_DAYS
      INBOX_CLEANUP_INTERVAL: vault:production/data/tmbiz-info/finance/batch-worker#INBOX_CLEANUP_INTERVAL
      POSTGRES_DB: vault:production/data/tmbiz-info/finance/batch-worker#POSTGRES_DB
      POSTGRES_HOST: vault:production/data/tmbiz-info/finance/batch-worker#POSTGRES_HOST
      POSTGRES_PASSWORD: vault:production/data/tmbiz-info/finance/batch-worker#POSTGRES_PASSWORD
      POSTGRES_POOL_MAX: vault:production/data/tmbiz-info/finance/batch-worker#POSTGRES_POOL_MAX
      POSTGRES_POOL_MIN: vault:production/data/tmbiz-info/finance/batch-worker#POSTGRES_POOL_MIN
      POSTGRES_PORT: vault:production/data/tmbiz-info/finance/batch-worker#POSTGRES_PORT
      POSTGRES_USER: vault:production/data/tmbiz-info/finance/batch-worker#POSTGRES_USER
      REDIS_DB: vault:production/data/tmbiz-info/finance/batch-worker#REDIS_DB
      REDIS_HOST: vault:production/data/tmbiz-info/finance/batch-worker#REDIS_HOST
      REDIS_PASSWORD: vault:production/data/tmbiz-info/finance/batch-worker#REDIS_PASSWORD
      REDIS_PORT: vault:production/data/tmbiz-info/finance/batch-worker#REDIS_PORT
      USER_MANAGEMENT_API_KEY: vault:production/data/tmbiz-info/finance/batch-worker#USER_MANAGEMENT_API_KEY
  tls-tmbiz.info:
    type: kubernetes.io/tls
    data:
      tls.crt: ""
      tls.key: ""
